---
- hosts: master
  gather_facts: False

- include: wait_for_all_pods_ready.yml

- include: ../KubeNow/playbooks/install-shared-vol-nfs.yml
  vars:
    nfs_server: "{{nfs_server}}"
    nfs_vol_size: "{{nfs_vol_size}}"
    nfs_path: "{{nfs_path}}"
  when:
    (nfs_vol_size | int) > 0

- include: ../KubeNow/playbooks/install-heketi-gluster.yml
  when:
    nfs_vol_size is undefined or (nfs_vol_size | int) == 0

- include: ../KubeNow/playbooks/create-pvc.yml
  vars:
    name: "{{pvc_name}}"
    storage: "{{pvc_storage}}"

- include: jupyter.yml
  vars:
    jupyter_chart_version: "{{jupyter_chart_version}}"
    hostname: "{{jupyter_hostname}}"
    jupyter_image_tag: "{{jupyter_image_tag}}"
    jupyter_password: "{{jupyter_password}}"
    jupyter_pvc: "{{jupyter_pvc}}"
    jupyter_resource_req_cpu: "{{jupyter_resource_req_cpu}}"
    jupyter_resource_req_memory: "{{jupyter_resource_req_memory}}"
    nologging: "{{jupyter_nologging}}"

- include: luigi/main.yml
  vars:
    hostname: "{{luigi_hostname}}"
    luigi_resource_req_memory: "{{luigi_resource_req_memory}}"
    luigi_resource_req_cpu: "{{luigi_resource_req_cpu}}"

- include: gluster-s3.yml
  vars:
    glusters3_release_name: "{{glusters3_release_name}}"
    glusters3_main_pvc_size: "{{glusters3_main_pvc_size}}"
    glusters3_meta_pvc_size: "{{glusters3_meta_pvc_size}}"
    glusters3_account: "{{glusters3_account}}"
    glusters3_user: "{{glusters3_user}}"
    glusters3_password: "{{glusters3_password}}"

- include: pachyderm.yml
  vars:
    pachyderm_release_name: "{{pachyderm_release_name}}"
    pachyderm_etcd_pvc_size: "{{pachyderm_etcd_pvc_size}}"
    pachyderm_glusters3_accesskey: "{{pachyderm_glusters3_accesskey}}"
    pachyderm_glusters3_secretkey: "{{pachyderm_glusters3_secretkey}}"

