---
- hosts: master
  gather_facts: False
  vars:
    nologging: False
  tasks:
    - name: install pachyderm
      command: >
        helm upgrade --install 
        --set credentials=s3,s3.accessKey="{{ pachyderm_glusters3_accesskey }}",s3.secretKey="{{ pachyderm_glusters3_secretkey }}",s3.bucketName=defaultbucket,s3.endpoint=gluster-s3-service.default.svc.cluster.local:8080,etcd.persistence.enabled=true,etcd.persistence.accessMode=ReadWriteMany,etcd.resources.requests.cpu=1,etcd.resources.requests.memory=1G,pachd.resources.requests.cpu=1,pachd.resources.requests.memory=1G
        "{{pachyderm_release_name}}" stable/pachyderm